"""Granite-backed strategy explanation client.

This is a thin adapter over the swappable :class:`~app.llm.base.GraniteProvider`.
It preserves the original ``GraniteClient`` public contract
(``GraniteClient()`` + ``await explain_strategy(...)`` returning
:class:`AIExplanationResponse`) so the existing
:mod:`app.services.explanation_service` keeps working unchanged.

Behaviour:
* When a real Granite provider is configured, the explanation is generated by
  the model from a race-engineer prompt.
* When no provider is available (offline ``echo`` provider, missing creds, or a
  provider error), it falls back to a deterministic template so the
  ``/api/explain/`` endpoint always returns sensible text and never 500s.
"""

from __future__ import annotations

from typing import List, Optional

from app.llm.base import GraniteProvider
from app.llm.factory import get_llm_provider
from app.prompts.granite_prompts import (
    EXPLANATION_SYSTEM_PROMPT,
    build_explanation_prompt,
)
from app.schemas.ai import AIExplanationResponse
from app.utils.logger import logger

# Marker emitted by the offline echo provider; signals we should use the
# deterministic template instead of the raw provider text.
_ECHO_MARKER = "[offline-echo provider]"


class GraniteClient:
    """Adapter exposing strategy explanation over the Granite provider."""

    def __init__(self, provider: Optional[GraniteProvider] = None) -> None:
        # Default to the shared singleton; allow injection for tests.
        self._provider = provider or get_llm_provider()

    @staticmethod
    def _template_explanation(
        recommendation: str,
        confidence: float,
        risk: str,
        reasons: List[str],
    ) -> str:
        """Deterministic fallback (matches the original client's wording)."""
        reason_text = ", ".join(reasons) if reasons else "current race conditions"
        return (
            f"{recommendation} recommended with {confidence:.0%} confidence "
            f"({risk} risk) due to {reason_text}."
        )

    async def explain_strategy(
        self,
        recommendation: str,
        confidence: float,
        risk: str,
        reasons: List[str],
    ) -> AIExplanationResponse:
        template = self._template_explanation(
            recommendation, confidence, risk, reasons
        )

        prompt = build_explanation_prompt(
            recommendation=recommendation,
            confidence=f"{confidence:.0%}",
            risk=risk,
            reasons=", ".join(reasons) if reasons else "n/a",
        )

        try:
            result = await self._provider.agenerate(
                prompt,
                system=EXPLANATION_SYSTEM_PROMPT,
                max_tokens=256,
                temperature=0.3,
            )
            text = (result.text or "").strip()
            # Use the model output only if it is real (non-empty and not the
            # offline echo debug string); otherwise fall back to the template.
            if text and _ECHO_MARKER not in text:
                explanation = text
            else:
                explanation = template
        except Exception as exc:  # noqa: BLE001 - explanation must never 500
            logger.warning("Granite explanation failed (%s); using template.", exc)
            explanation = template

        return AIExplanationResponse(explanation=explanation)
